CREATE OR REPLACE PROCEDURE SP_INSERIR_MORTALIDADE (
    P_ID_LOTE_FK IN NUMBER,
    P_DATA_MORTALIDADE IN DATE,
    P_QUANTIDADE_MORTA IN NUMBER,
    P_OBSERVACAO IN VARCHAR2,
    P_PERCENTUAL_MORTALIDADE OUT NUMBER -- Parâmetro de saída
)
IS
    V_QTD_INICIAL NUMBER;
    V_TOTAL_MORTALIDADES NUMBER;
BEGIN
    -- Inserção dos dados
    INSERT INTO TAB_MORTALIDADE (ID_LOTE_FK, DATA_MORTALIDADE, QUANTIDADE_MORTA, OBSERVACAO)
    VALUES (P_ID_LOTE_FK, P_DATA_MORTALIDADE, P_QUANTIDADE_MORTA, P_OBSERVACAO);
 
    SELECT QUANTIDADE_INICIAL INTO V_QTD_INICIAL
    FROM TAB_LOTE_AVES
    WHERE ID_LOTE = P_ID_LOTE_FK;

    SELECT SUM(QUANTIDADE_MORTA) INTO V_TOTAL_MORTALIDADES
    FROM TAB_MORTALIDADE
    WHERE ID_LOTE_FK = P_ID_LOTE_FK;
   
    IF V_TOTAL_MORTALIDADES > V_QTD_INICIAL THEN
        RAISE_APPLICATION_ERROR(-20002, 'A soma das mortalidades ultrapassa a quantidade inicial do lote.');
    END IF;
    
    IF V_QTD_INICIAL > 0 THEN
        P_PERCENTUAL_MORTALIDADE := (V_TOTAL_MORTALIDADES / V_QTD_INICIAL) * 100;
    ELSE
        P_PERCENTUAL_MORTALIDADE := 0;
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_PERCENTUAL_MORTALIDADE := -1; -- Retorna um valor de erro
        RAISE;
END;
/